name: CD
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: cd deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd /root/financial-accounting-front
            git pull origin main
            yarn
            yarn build
            rm -rf /root/front/*
            mv /root/financial-accounting-front/dist/* /root/front/
